Compile: main.c ./Patricia/pat.c ./Lista/listadoc.c ./TST/tst.c ./IndiceInvertido/indiceInvertido.c
	gcc `pkg-config --cflags gtk+-3.0` -o r main.c ./Patricia/pat.c ./Lista/listadoc.c ./TST/tst.c ./IndiceInvertido/indiceInvertido.c `pkg-config --libs gtk+-3.0`
run:
	./r
